# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/test-docs-update',
                'doc_host': 'https://harishmohanraj.github.io',
                'git_url': 'https://github.com/harishmohanraj/test-docs-update',
                'lib_path': 'test_docs_update'},
  'syms': {'test_docs_update.core': {'test_docs_update.core.foo': ('core.html#foo', 'test_docs_update/core.py')}}}
